version: 2.1
orbs:
  datacamp-ecr: datacamp/ecr@0.0.4
  datacamp-deploy: datacamp/deploy@0.0.11
workflows:
  version: 2.1 
  build_and_deploy:
    jobs:
      - datacamp-ecr/build_and_push_image_to_ecr:
          context: org-global
          aws-access-key-id: $STAGING_AWS_ACCESS_KEY_ID
          aws-secret-access-key: $STAGING_AWS_SECRET_ACCESS_KEY
          account-url: $STAGING_ECR_URL
          extra-docker-args: "--build-arg NPM_TOKEN=$NPM_TOKEN"
      - datacamp-deploy/deploy:
          context: org-global
          service-name: ast-viewer
          ecs-deploy-url: $STAGING_DEPLOY_URL
          ecs-deploy-password: $STAGING_ECS_DEPLOY_PASSWORD
          extra-env: "ENVIRONMENT=staging DESIRED_COUNT=1"
      # - deploy-to-prod:
      #     context: org-global
      #     filters:
      #       tags:
      #         only: /^v.*/
      #       branches:
      #         ignore: /.*/
