version: 2.1
orbs:
  datacamp-ecr: datacamp/ecr@0.0.6
  datacamp-deploy: datacamp/deploy@0.0.25
workflows:
  version: 2.1 
  build_and_deploy:
    jobs:
      - datacamp-ecr/build_and_push_image_to_ecr:
          context: org-global
          aws-access-key-id: $STAGING_AWS_ACCESS_KEY_ID
          aws-secret-access-key: $STAGING_AWS_SECRET_ACCESS_KEY
          account-url: $STAGING_ECR_URL
          extra-docker-args: "--build-arg NPM_TOKEN=$NPM_TOKEN"
      - datacamp-deploy/deploy:
          context: org-global
          requires:
            - datacamp-ecr/build_and_push_image_to_ecr
          ecs-deploy-url: $STAGING_DEPLOY_URL
          ecs-deploy-password: $STAGING_ECS_DEPLOY_PASSWORD
          extra-env: "DESIRED_COUNT=1 CLUSTER=datacamp-services SERVICE=ast-viewer"
          filters:
            branches:
              only: master
      - datacamp-ecr/pull_push_to_account:
          context: org-global
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - datacamp-deploy/deploy:
          context: org-global
          requires:
            - datacamp-ecr/pull_push_to_account
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          ecs-deploy-url: $PROD_DEPLOY_URL
          ecs-deploy-password: $PROD_ECS_DEPLOY_PASSWORD
          extra-env: "DESIRED_COUNT=2 CLUSTER=datacamp-services SERVICE=ast-viewer"
      - datacamp-deploy/backstage-deploy:
          context: org-global
          requires:
            - datacamp-ecr/build_and_push_image_to_ecr
          extra-env: "SERVICE=ast-viewer-$CIRCLE_BRANCH CLUSTER=backstage DESIRED_COUNT=1"
          filters:
            branches:
              only: /backstage-.*/
